# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
#  allow_failures:
#  - julia: nightly

# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION < v"0.7.0-DEV" || (using Pkg); d="https://github.com/JuliaString" ; for n in ("ModuleInterfaceTools", "StrAPI", "CharSetEncodings", "Chars", "StrBase") ; Pkg.clone("$d/$n.jl") ; end ; Pkg.add("Format"); Pkg.clone("$d/StrLiterals.jl"); Pkg.clone(pwd()); Pkg.test("StrFormat"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'VERSION < v"0.7.0-DEV" || (using Pkg); cd(Pkg.dir("StrFormat")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'VERSION < v"0.7.0-DEV" || (using Pkg); cd(Pkg.dir("StrFormat")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
