name = "StrFormat"
desc = "Extension for StrLiterals, adds support for C/Python/type-driven formatting"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings", "Literals", "printf", "Format"]
license = "MIT"
uuid = "a5a47323-cf2a-443b-a747-99a2b29c4966"

[deps]
Pkg     = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test    = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

Format      = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8" # 9wb580eyjv4k3iej
StrLiterals = "627f7b36-cfa1-4420-8f93-de9d4fe56cdc" # 8462oq09ek07knos
